services:
  - type: web
    name: crm-business-system
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_BUCKET_NAME
        sync: false
    healthCheckPath: /api/dashboard/stats
